version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/code
    command: /usr/local/bin/gunicorn streaming.wsgi:application -w 2 -b :8000

  nginx:
    image: nginx:1.23.4
    restart: always
    ports:
      - "2800:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
